# Generated by Django 5.1.4 on 2025-01-09 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('sentence_examples', models.JSONField(blank=True, null=True)),
                ('translations', models.ManyToManyField(related_name='translated_from', to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_language', models.CharField(max_length=50)),
                ('learning_languages', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seen_words', models.ManyToManyField(related_name='seen_by_users', to='api.word')),
            ],
        ),
    ]
