services:
  backend:
    build:
      context: ../backend
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    env_file:
      - ../.env  # Load environment variables for backend
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "19000:19000"  # React Native Metro Bundler
      - "19001:19001"  # React Native debugger
    volumes:
      - ../frontend:/app

  db:
    image: postgres:14
    env_file:
      - ../.env  # Load environment variables for db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
